/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DcAdminZ9x7RouteImport } from './routes/dc-admin-z9x7'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartyBCaseIdRouteImport } from './routes/party-b.$caseId'
import { Route as CourtSlugRouteImport } from './routes/court.$slug'
import { Route as CaseSlugRouteImport } from './routes/case.$slug'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DcAdminZ9x7Route = DcAdminZ9x7RouteImport.update({
  id: '/dc-admin-z9x7',
  path: '/dc-admin-z9x7',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyBCaseIdRoute = PartyBCaseIdRouteImport.update({
  id: '/party-b/$caseId',
  path: '/party-b/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtSlugRoute = CourtSlugRouteImport.update({
  id: '/court/$slug',
  path: '/court/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseSlugRoute = CaseSlugRouteImport.update({
  id: '/case/$slug',
  path: '/case/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dc-admin-z9x7': typeof DcAdminZ9x7Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/case/$slug': typeof CaseSlugRoute
  '/court/$slug': typeof CourtSlugRoute
  '/party-b/$caseId': typeof PartyBCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dc-admin-z9x7': typeof DcAdminZ9x7Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/case/$slug': typeof CaseSlugRoute
  '/court/$slug': typeof CourtSlugRoute
  '/party-b/$caseId': typeof PartyBCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dc-admin-z9x7': typeof DcAdminZ9x7Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/case/$slug': typeof CaseSlugRoute
  '/court/$slug': typeof CourtSlugRoute
  '/party-b/$caseId': typeof PartyBCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/dc-admin-z9x7'
    | '/sitemap.xml'
    | '/submit'
    | '/case/$slug'
    | '/court/$slug'
    | '/party-b/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/dc-admin-z9x7'
    | '/sitemap.xml'
    | '/submit'
    | '/case/$slug'
    | '/court/$slug'
    | '/party-b/$caseId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/dc-admin-z9x7'
    | '/sitemap.xml'
    | '/submit'
    | '/case/$slug'
    | '/court/$slug'
    | '/party-b/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  DcAdminZ9x7Route: typeof DcAdminZ9x7Route
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  CaseSlugRoute: typeof CaseSlugRoute
  CourtSlugRoute: typeof CourtSlugRoute
  PartyBCaseIdRoute: typeof PartyBCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dc-admin-z9x7': {
      id: '/dc-admin-z9x7'
      path: '/dc-admin-z9x7'
      fullPath: '/dc-admin-z9x7'
      preLoaderRoute: typeof DcAdminZ9x7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party-b/$caseId': {
      id: '/party-b/$caseId'
      path: '/party-b/$caseId'
      fullPath: '/party-b/$caseId'
      preLoaderRoute: typeof PartyBCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/court/$slug': {
      id: '/court/$slug'
      path: '/court/$slug'
      fullPath: '/court/$slug'
      preLoaderRoute: typeof CourtSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$slug': {
      id: '/case/$slug'
      path: '/case/$slug'
      fullPath: '/case/$slug'
      preLoaderRoute: typeof CaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  DcAdminZ9x7Route: DcAdminZ9x7Route,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  CaseSlugRoute: CaseSlugRoute,
  CourtSlugRoute: CourtSlugRoute,
  PartyBCaseIdRoute: PartyBCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
